import struct

MAGIC_BYTES = b'ROBY'
VERSION = 1
HEADER_FORMAT = '<4sHII'  
HEADER_SIZE = struct.calcsize(HEADER_FORMAT)
ENTRY_METADATA_FMT = '<QQ32sdI'
ENTRY_METADATA_SIZE = struct.calcsize(ENTRY_METADATA_FMT) 

MAX_PATH_LENGTH = 1024
MAX_FILE_SIZE = 1024 * 1024 * 1024 * 4 
