import struct


MAGIC_BYTES = b'ROBY'
VERSION = 1
HEADER_FORMAT = '<4sHII'  
HEADER_SIZE = struct.calcsize(HEADER_FORMAT)
INDEX_ENTRY_FIXED_FMT = '<H8sQQ32s' 

MAX_PATH_LENGTH = 1024
MAX_FILE_SIZE = 1024 * 1024 * 1024 * 4 
